services:
  mongodb:
    image: mongo:7.0
    container_name: ecommerce-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ecommerce-backend
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./backend/src:/app/src
    env_file:
      - path: ./backend/.env
        required: false
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ecommerce-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
    environment:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
    depends_on:
      - backend

volumes:
  mongo-data:


